---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: bitsarvi/oci-cpi-release
    tag: "latest"
inputs:
  - name: bosh-cpi-src
  - name: version-semver
outputs:
  - name: candidate
run:
  path: bosh-cpi-src/ci/tasks/build-candidate.sh
