---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: bitsarvi/oci-cpi-release
    tag: "latest"
inputs:
  - name: bosh-cpi-src
#  - name: bosh-init
  - name: deployment
run:
  path: bosh-cpi-src/ci/tasks/teardown-director.sh
params:
  BOSH_LOG_LEVEL: debug
  BOSH_LOG_PATH:  ./bosh-init.log
