---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: bitsarvi/oci-cpi-release
    tag: "latest"
inputs:
  - name: bosh-cpi-src
run:
  path: bosh-cpi-src/ci/tasks/unit-tests.sh
