---
groups:
  - name: bosh-oracle-cpi-cleanup
    jobs:
      - teardown-infrastructure

jobs:

  - name: teardown-infrastructure
    plan:
      - aggregate:
        - {trigger: false, get: bosh-cpi-src,   resource: bosh-cpi-src-in}

      - task: teardown-infrastructure
        file: bosh-cpi-src/ci/tasks/teardown-infrastructure.yml
        params:
          oracle_tenancy:                 {{oracle_tenancy}}
          oracle_user:                    {{oracle_user}}
          oracle_compartment_id:          {{oracle_compartment_id}}
          oracle_compartment_name:        {{oracle_compartment_name}}
          oracle_region:                  {{oracle_region}}
          oracle_ad:                      {{oracle_ad}}
          oracle_fingerprint:             {{oracle_fingerprint}}
          oracle_apikey:                  {{oracle_apikey}}
          oracle_ssh_public_key:          {{oracle_ssh_public_key}}
          oracle_ssh_private_key:         {{oracle_ssh_private_key}}


resources:
  - name: bosh-cpi-src-in
    type: git
    source:
      uri: https://((github-repo))
      branch: ((github-branch))
      ignore_paths:
        - .final_builds/**/*.yml
        - releases/**/*.yml
